// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/riku179/regisys-server/design
// --out=$(GOPATH)/src/github.com/riku179/regisys-server
// --version=v1.1.0-dirty
//
// API "regisys": items Resource Client
//
// The content of this file is auto-generated, DO NOT MODIFY

package client

import (
	"bytes"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"golang.org/x/net/context"
)

// AddItemsPath computes a request path to the add action of items.
func AddItemsPath() string {

	return fmt.Sprintf("/item")
}

// Add item
func (c *Client) AddItems(ctx context.Context, path string, payload *AddItemPayload, contentType string) (*http.Response, error) {
	req, err := c.NewAddItemsRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewAddItemsRequest create the request corresponding to the add action endpoint of the items resource.
func (c *Client) NewAddItemsRequest(ctx context.Context, path string, payload *AddItemPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType != "*/*" {
		header.Set("Content-Type", contentType)
	}
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}

// DeleteItemsPath computes a request path to the delete action of items.
func DeleteItemsPath(id int) string {
	param0 := strconv.Itoa(id)

	return fmt.Sprintf("/item/%s", param0)
}

// Delete item
func (c *Client) DeleteItems(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewDeleteItemsRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewDeleteItemsRequest create the request corresponding to the delete action endpoint of the items resource.
func (c *Client) NewDeleteItemsRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("DELETE", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}

// ModifyItemsPath computes a request path to the modify action of items.
func ModifyItemsPath(id int) string {
	param0 := strconv.Itoa(id)

	return fmt.Sprintf("/item/%s", param0)
}

// Modify item
func (c *Client) ModifyItems(ctx context.Context, path string, payload *ModifyItemPayload, contentType string) (*http.Response, error) {
	req, err := c.NewModifyItemsRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewModifyItemsRequest create the request corresponding to the modify action endpoint of the items resource.
func (c *Client) NewModifyItemsRequest(ctx context.Context, path string, payload *ModifyItemPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("PUT", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType != "*/*" {
		header.Set("Content-Type", contentType)
	}
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}

// ShowItemsPath computes a request path to the show action of items.
func ShowItemsPath() string {

	return fmt.Sprintf("/item")
}

// Get items
func (c *Client) ShowItems(ctx context.Context, path string, user *int) (*http.Response, error) {
	req, err := c.NewShowItemsRequest(ctx, path, user)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowItemsRequest create the request corresponding to the show action endpoint of the items resource.
func (c *Client) NewShowItemsRequest(ctx context.Context, path string, user *int) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if user != nil {
		tmp15 := strconv.Itoa(*user)
		values.Set("user", tmp15)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		c.JWTSigner.Sign(req)
	}
	return req, nil
}
