# docker-compose.yml for production
# this version not expose ports
version: "2"
services:
  app:
    image: golang:1.7
    volumes:
      - 'lib:/go'
      - '.:/go/src/github.com/riku179/regisys-server'
    working_dir: /go/src/github.com/riku179/regisys-server
    entrypoint: './wait-for-it.sh -t 60 db:3306 -- '
    command: 'go run main.go jwt.go items.go orders.go user.go swagger.go'
    environment:
      - HOST_ADDR=0.0.0.0:8080
      - MYSQL_DATABASE=regisys
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=foobar
      - DEBUG=false
    links:
      - db
    depends_on:
      - db

  db:
    image: mariadb
    volumes:
      - data:/var/lib/mysql
    command: '-C utf8'
    environment:
      - MYSQL_DATABASE=regisys
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=foobar
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - TZ=Asia/Tokyo


volumes:
  lib:
    driver: local
  data:
    driver: local
