// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/riku179/regisys-server/design
// --out=$(GOPATH)/src/github.com/riku179/regisys-server
// --version=v1.1.0-dirty
//
// API "regisys": Application Contexts
//
// The content of this file is auto-generated, DO NOT MODIFY

package app

import (
	"github.com/goadesign/goa"
	"golang.org/x/net/context"
	"net/http"
	"strconv"
	"time"
)

// AddItemsContext provides the items add action context.
type AddItemsContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Payload *AddGoodsPayload
}

// NewAddItemsContext parses the incoming request URL and body, performs validations and creates the
// context used by the items controller add action.
func NewAddItemsContext(ctx context.Context, r *http.Request, service *goa.Service) (*AddItemsContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := AddItemsContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// NoContent sends a HTTP response with status code 204.
func (ctx *AddItemsContext) NoContent() error {
	ctx.ResponseData.WriteHeader(204)
	return nil
}

// DeleteItemsContext provides the items delete action context.
type DeleteItemsContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID int
}

// NewDeleteItemsContext parses the incoming request URL and body, performs validations and creates the
// context used by the items controller delete action.
func NewDeleteItemsContext(ctx context.Context, r *http.Request, service *goa.Service) (*DeleteItemsContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := DeleteItemsContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		if id, err2 := strconv.Atoi(rawID); err2 == nil {
			rctx.ID = id
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("id", rawID, "integer"))
		}
	}
	return &rctx, err
}

// NoContent sends a HTTP response with status code 204.
func (ctx *DeleteItemsContext) NoContent() error {
	ctx.ResponseData.WriteHeader(204)
	return nil
}

// Forbidden sends a HTTP response with status code 403.
func (ctx *DeleteItemsContext) Forbidden() error {
	ctx.ResponseData.WriteHeader(403)
	return nil
}

// NotFound sends a HTTP response with status code 404.
func (ctx *DeleteItemsContext) NotFound() error {
	ctx.ResponseData.WriteHeader(404)
	return nil
}

// ModifyItemsContext provides the items modify action context.
type ModifyItemsContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID      int
	Payload *ModifyGoodsPayload
}

// NewModifyItemsContext parses the incoming request URL and body, performs validations and creates the
// context used by the items controller modify action.
func NewModifyItemsContext(ctx context.Context, r *http.Request, service *goa.Service) (*ModifyItemsContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ModifyItemsContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		if id, err2 := strconv.Atoi(rawID); err2 == nil {
			rctx.ID = id
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("id", rawID, "integer"))
		}
	}
	return &rctx, err
}

// NoContent sends a HTTP response with status code 204.
func (ctx *ModifyItemsContext) NoContent() error {
	ctx.ResponseData.WriteHeader(204)
	return nil
}

// NotFound sends a HTTP response with status code 404.
func (ctx *ModifyItemsContext) NotFound() error {
	ctx.ResponseData.WriteHeader(404)
	return nil
}

// ShowItemsContext provides the items show action context.
type ShowItemsContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	User *int
}

// NewShowItemsContext parses the incoming request URL and body, performs validations and creates the
// context used by the items controller show action.
func NewShowItemsContext(ctx context.Context, r *http.Request, service *goa.Service) (*ShowItemsContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ShowItemsContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramUser := req.Params["user"]
	if len(paramUser) > 0 {
		rawUser := paramUser[0]
		if user, err2 := strconv.Atoi(rawUser); err2 == nil {
			tmp4 := user
			tmp3 := &tmp4
			rctx.User = tmp3
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("user", rawUser, "integer"))
		}
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ShowItemsContext) OK(r GoaExampleRegisysItemsCollection) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.example.regisys.items+json; type=collection")
	if r == nil {
		r = GoaExampleRegisysItemsCollection{}
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// NotFound sends a HTTP response with status code 404.
func (ctx *ShowItemsContext) NotFound() error {
	ctx.ResponseData.WriteHeader(404)
	return nil
}

// SigninJWTContext provides the jwt signin action context.
type SigninJWTContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Authorization string
	IsMember      bool
}

// NewSigninJWTContext parses the incoming request URL and body, performs validations and creates the
// context used by the jwt controller signin action.
func NewSigninJWTContext(ctx context.Context, r *http.Request, service *goa.Service) (*SigninJWTContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := SigninJWTContext{Context: ctx, ResponseData: resp, RequestData: req}
	headerAuthorization := req.Header["Authorization"]
	if len(headerAuthorization) == 0 {
		err = goa.MergeErrors(err, goa.MissingHeaderError("Authorization"))
	} else {
		rawAuthorization := headerAuthorization[0]
		req.Params["Authorization"] = []string{rawAuthorization}
		rctx.Authorization = rawAuthorization
	}
	paramIsMember := req.Params["is_member"]
	if len(paramIsMember) == 0 {
		err = goa.MergeErrors(err, goa.MissingParamError("is_member"))
	} else {
		rawIsMember := paramIsMember[0]
		if isMember, err2 := strconv.ParseBool(rawIsMember); err2 == nil {
			rctx.IsMember = isMember
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("is_member", rawIsMember, "boolean"))
		}
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *SigninJWTContext) OK(r *GoaExampleToken) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.example.token+json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// Unauthorized sends a HTTP response with status code 401.
func (ctx *SigninJWTContext) Unauthorized() error {
	ctx.ResponseData.WriteHeader(401)
	return nil
}

// AddOrdersContext provides the orders add action context.
type AddOrdersContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Payload *AddOrderPayload
}

// NewAddOrdersContext parses the incoming request URL and body, performs validations and creates the
// context used by the orders controller add action.
func NewAddOrdersContext(ctx context.Context, r *http.Request, service *goa.Service) (*AddOrdersContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := AddOrdersContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// NoContent sends a HTTP response with status code 204.
func (ctx *AddOrdersContext) NoContent() error {
	ctx.ResponseData.WriteHeader(204)
	return nil
}

// Forbidden sends a HTTP response with status code 403.
func (ctx *AddOrdersContext) Forbidden() error {
	ctx.ResponseData.WriteHeader(403)
	return nil
}

// DeleteOrdersContext provides the orders delete action context.
type DeleteOrdersContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID int
}

// NewDeleteOrdersContext parses the incoming request URL and body, performs validations and creates the
// context used by the orders controller delete action.
func NewDeleteOrdersContext(ctx context.Context, r *http.Request, service *goa.Service) (*DeleteOrdersContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := DeleteOrdersContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		if id, err2 := strconv.Atoi(rawID); err2 == nil {
			rctx.ID = id
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("id", rawID, "integer"))
		}
	}
	return &rctx, err
}

// NoContent sends a HTTP response with status code 204.
func (ctx *DeleteOrdersContext) NoContent() error {
	ctx.ResponseData.WriteHeader(204)
	return nil
}

// Forbidden sends a HTTP response with status code 403.
func (ctx *DeleteOrdersContext) Forbidden() error {
	ctx.ResponseData.WriteHeader(403)
	return nil
}

// NotFound sends a HTTP response with status code 404.
func (ctx *DeleteOrdersContext) NotFound() error {
	ctx.ResponseData.WriteHeader(404)
	return nil
}

// ShowOrdersContext provides the orders show action context.
type ShowOrdersContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Date *time.Time
	User *string
}

// NewShowOrdersContext parses the incoming request URL and body, performs validations and creates the
// context used by the orders controller show action.
func NewShowOrdersContext(ctx context.Context, r *http.Request, service *goa.Service) (*ShowOrdersContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ShowOrdersContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramDate := req.Params["date"]
	if len(paramDate) > 0 {
		rawDate := paramDate[0]
		if date, err2 := time.Parse(time.RFC3339, rawDate); err2 == nil {
			tmp7 := &date
			rctx.Date = tmp7
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("date", rawDate, "datetime"))
		}
	}
	paramUser := req.Params["user"]
	if len(paramUser) > 0 {
		rawUser := paramUser[0]
		rctx.User = &rawUser
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ShowOrdersContext) OK(r GoaExampleOrdersCollection) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.example.orders+json; type=collection")
	if r == nil {
		r = GoaExampleOrdersCollection{}
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// NotFound sends a HTTP response with status code 404.
func (ctx *ShowOrdersContext) NotFound() error {
	ctx.ResponseData.WriteHeader(404)
	return nil
}

// AddUserContext provides the user add action context.
type AddUserContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Payload *AddUserPayload
}

// NewAddUserContext parses the incoming request URL and body, performs validations and creates the
// context used by the user controller add action.
func NewAddUserContext(ctx context.Context, r *http.Request, service *goa.Service) (*AddUserContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := AddUserContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// NoContent sends a HTTP response with status code 204.
func (ctx *AddUserContext) NoContent() error {
	ctx.ResponseData.WriteHeader(204)
	return nil
}

// Forbidden sends a HTTP response with status code 403.
func (ctx *AddUserContext) Forbidden() error {
	ctx.ResponseData.WriteHeader(403)
	return nil
}

// ModifyUserContext provides the user modify action context.
type ModifyUserContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID      int
	Payload *ModifyUserPayload
}

// NewModifyUserContext parses the incoming request URL and body, performs validations and creates the
// context used by the user controller modify action.
func NewModifyUserContext(ctx context.Context, r *http.Request, service *goa.Service) (*ModifyUserContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ModifyUserContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		if id, err2 := strconv.Atoi(rawID); err2 == nil {
			rctx.ID = id
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("id", rawID, "integer"))
		}
	}
	return &rctx, err
}

// NoContent sends a HTTP response with status code 204.
func (ctx *ModifyUserContext) NoContent() error {
	ctx.ResponseData.WriteHeader(204)
	return nil
}

// Forbidden sends a HTTP response with status code 403.
func (ctx *ModifyUserContext) Forbidden() error {
	ctx.ResponseData.WriteHeader(403)
	return nil
}

// NotFound sends a HTTP response with status code 404.
func (ctx *ModifyUserContext) NotFound() error {
	ctx.ResponseData.WriteHeader(404)
	return nil
}

// ShowUserContext provides the user show action context.
type ShowUserContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID int
}

// NewShowUserContext parses the incoming request URL and body, performs validations and creates the
// context used by the user controller show action.
func NewShowUserContext(ctx context.Context, r *http.Request, service *goa.Service) (*ShowUserContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ShowUserContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		if id, err2 := strconv.Atoi(rawID); err2 == nil {
			rctx.ID = id
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("id", rawID, "integer"))
		}
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ShowUserContext) OK(r *GoaExampleUser) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.example.user+json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// NotFound sends a HTTP response with status code 404.
func (ctx *ShowUserContext) NotFound() error {
	ctx.ResponseData.WriteHeader(404)
	return nil
}

// ShowListUserContext provides the user showList action context.
type ShowListUserContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
}

// NewShowListUserContext parses the incoming request URL and body, performs validations and creates the
// context used by the user controller showList action.
func NewShowListUserContext(ctx context.Context, r *http.Request, service *goa.Service) (*ShowListUserContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ShowListUserContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ShowListUserContext) OK(r GoaExampleUserCollection) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.example.user+json; type=collection")
	if r == nil {
		r = GoaExampleUserCollection{}
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}
