// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=regisys/design
// --force=true
// --out=$(GOPATH)/src/regisys
// --version=v1.1.0-dirty
//
// API "regisys": swagger TestHelpers
//
// The content of this file is auto-generated, DO NOT MODIFY

package test
