// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/riku179/regisys/design
// --out=$(GOPATH)/src/github.com/riku179/regisys
// --version=v1.1.0-dirty
//
// API "regisys": Model Helpers
//
// The content of this file is auto-generated, DO NOT MODIFY

package models

import (
	"github.com/goadesign/goa"
	"github.com/jinzhu/gorm"
	"github.com/riku179/regisys/app"
	"golang.org/x/net/context"
	"time"
)

// MediaType Retrieval Functions

// ListGoaExampleRegisysItems returns an array of view: default.
func (m *ItemsDB) ListGoaExampleRegisysItems(ctx context.Context) []*app.GoaExampleRegisysItems {
	defer goa.MeasureSince([]string{"goa", "db", "goaExampleRegisysItems", "listgoaExampleRegisysItems"}, time.Now())

	var native []*Items
	var objs []*app.GoaExampleRegisysItems
	err := m.Db.Scopes().Table(m.TableName()).Find(&native).Error

	if err != nil {
		goa.LogError(ctx, "error listing Items", "error", err.Error())
		return objs
	}

	for _, t := range native {
		objs = append(objs, t.ItemsToGoaExampleRegisysItems())
	}

	return objs
}

// ItemsToGoaExampleRegisysItems loads a Items and builds the default view of media type GoaExampleRegisysItems.
func (m *Items) ItemsToGoaExampleRegisysItems() *app.GoaExampleRegisysItems {
	items := &app.GoaExampleRegisysItems{}
	items.ID = m.ID
	items.ItemName = m.ItemName
	items.MemberPrice = m.MemberPrice
	items.Price = m.Price
	items.Quantity = m.Quantity
	items.UserID = m.UserID

	return items
}

// OneGoaExampleRegisysItems loads a Items and builds the default view of media type GoaExampleRegisysItems.
func (m *ItemsDB) OneGoaExampleRegisysItems(ctx context.Context, id int) (*app.GoaExampleRegisysItems, error) {
	defer goa.MeasureSince([]string{"goa", "db", "goaExampleRegisysItems", "onegoaExampleRegisysItems"}, time.Now())

	var native Items
	err := m.Db.Scopes().Table(m.TableName()).Preload("Orders").Where("id = ?", id).Find(&native).Error

	if err != nil && err != gorm.ErrRecordNotFound {
		goa.LogError(ctx, "error getting Items", "error", err.Error())
		return nil, err
	}

	view := *native.ItemsToGoaExampleRegisysItems()
	return &view, err
}
