// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/riku179/regisys-server/design
// --out=$(GOPATH)/src/github.com/riku179/regisys-server
// --version=v1.1.0-dirty
//
// API "regisys": Model Helpers
//
// The content of this file is auto-generated, DO NOT MODIFY

package models

import (
	"time"

	"github.com/goadesign/goa"
	"github.com/jinzhu/gorm"
	"github.com/riku179/regisys-server/app"
	"golang.org/x/net/context"
)

// MediaType Retrieval Functions

// ListRegisysItems returns an array of view: default.
func (m *ItemsDB) ListRegisysItems(ctx context.Context) []*app.RegisysItems {
	defer goa.MeasureSince([]string{"goa", "db", "regisysItems", "listregisysItems"}, time.Now())

	var native []*Items
	var objs []*app.RegisysItems
	err := m.Db.Scopes().Table(m.TableName()).Find(&native).Error

	if err != nil {
		goa.LogError(ctx, "error listing Items", "error", err.Error())
		return objs
	}

	for _, t := range native {
		objs = append(objs, t.ItemsToRegisysItems())
	}

	return objs
}

// ItemsToRegisysItems loads a Items and builds the default view of media type RegisysItems.
func (m *Items) ItemsToRegisysItems() *app.RegisysItems {
	items := &app.RegisysItems{}
	items.ID = m.ID
	items.ItemName = m.ItemName
	items.MemberPrice = m.MemberPrice
	items.Price = m.Price
	items.Quantity = m.Quantity
	items.UserID = m.UserID

	return items
}

// OneRegisysItems loads a Items and builds the default view of media type RegisysItems.
func (m *ItemsDB) OneRegisysItems(ctx context.Context, id int) (*app.RegisysItems, error) {
	defer goa.MeasureSince([]string{"goa", "db", "regisysItems", "oneregisysItems"}, time.Now())

	var native Items
	err := m.Db.Scopes().Table(m.TableName()).Preload("Orders").Where("id = ?", id).Find(&native).Error

	if err != nil && err != gorm.ErrRecordNotFound {
		goa.LogError(ctx, "error getting Items", "error", err.Error())
		return nil, err
	}

	view := *native.ItemsToRegisysItems()
	return &view, err
}
